# Generated by Django 3.0.8 on 2020-08-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='davlenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(null=True, verbose_name='Nomer')),
                ('Value', models.FloatField(blank=True, null=True, verbose_name='Velichina')),
                ('Time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vremya dobavleniya')),
            ],
        ),
        migrations.CreateModel(
            name='temperatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(null=True, verbose_name='Nomer')),
                ('Value', models.FloatField(blank=True, null=True, verbose_name='Velichina')),
                ('Time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vremya dobavleniya')),
            ],
        ),
    ]
