# Generated by Django 3.0.8 on 2020-09-14 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mac_adr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='mac adres')),
            ],
        ),
        migrations.CreateModel(
            name='data_esp_t',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value_t', models.FloatField(blank=True, null=True, verbose_name='Velichina temp')),
                ('Time_t', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vremya dobavleniya')),
                ('mac_adr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.mac_adr', verbose_name='mac adres')),
            ],
        ),
        migrations.CreateModel(
            name='data_esp_mem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value_mem', models.FloatField(blank=True, null=True, verbose_name='Velichina temp')),
                ('Time_mem', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vremya dobavleniya')),
                ('mac_adr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.mac_adr', verbose_name='mac adres')),
            ],
        ),
    ]
