# Generated by Django 3.0.8 on 2020-08-25 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mac_adr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='mac adres')),
            ],
        ),
        migrations.CreateModel(
            name='data_esp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value_mem', models.FloatField(blank=True, null=True, verbose_name='Velichina mems')),
                ('Value_t', models.FloatField(blank=True, null=True, verbose_name='Velichina temp')),
                ('Time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vremya dobavleniya')),
                ('mac_adr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.mac_adr', verbose_name='mac adres')),
            ],
        ),
    ]
